// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGiay.API.Data;

#nullable disable

namespace WebBanGiay.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202095710_AddUserRole")]
    partial class AddUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebBanGiay.API.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Giày dành cho hoạt động thể thao",
                            Name = "Giày thể thao"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Giày lịch sự cho môi trường công sở",
                            Name = "Giày công sở"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Giày sneaker phong cách",
                            Name = "Giày sneaker"
                        });
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 0m,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Đen",
                            CreatedAt = new DateTime(2026, 2, 2, 9, 57, 9, 660, DateTimeKind.Utc).AddTicks(186),
                            Description = "Giày thể thao cao cấp Nike Air Max 270",
                            ImageUrl = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/u3rcvb1r7e9bjpxynzfn/air-max-270-mens-shoes-KkLcGR.png",
                            Name = "Nike Air Max 270",
                            Price = 3200000m,
                            ReviewCount = 0,
                            Size = "42",
                            Stock = 50
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 0m,
                            Brand = "Adidas",
                            CategoryId = 1,
                            Color = "Trắng",
                            CreatedAt = new DateTime(2026, 2, 2, 9, 57, 9, 660, DateTimeKind.Utc).AddTicks(1601),
                            Description = "Giày chạy bộ Adidas Ultraboost",
                            ImageUrl = "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Ultraboost_Light_Shoes_Black_GY9350_01_standard.jpg",
                            Name = "Adidas Ultraboost",
                            Price = 4500000m,
                            ReviewCount = 0,
                            Size = "41",
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 0m,
                            Brand = "Clarks",
                            CategoryId = 2,
                            Color = "Nâu",
                            CreatedAt = new DateTime(2026, 2, 2, 9, 57, 9, 660, DateTimeKind.Utc).AddTicks(1604),
                            Description = "Giày da Oxford cao cấp cho doanh nhân",
                            ImageUrl = "https://product.hstatic.net/200000033444/product/den_d_1_e7bb8cbe65014a1da5ca53e7b28cc42d_master.jpg",
                            Name = "Giày da Oxford",
                            Price = 2800000m,
                            ReviewCount = 0,
                            Size = "40",
                            Stock = 20
                        });
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("WebBanGiay.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Product", b =>
                {
                    b.HasOne("WebBanGiay.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Review", b =>
                {
                    b.HasOne("WebBanGiay.API.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebBanGiay.API.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
